name: Auto-EpicGame

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Docker container
        env:
          SHOW: 0
          NOTIFY: ${{ env.NOTIFY }}
          NOTIFY_TITLE: Auto-EpicGame
          EMAIL: ${{ env.EG_EMAIL }}
          PASSWORD: ${{ env.EG_PASSWORD }}
        run: |
          docker run -e SHOW=$SHOW \
                     -e NOTIFY=$NOTIFY \
                     -e NOTIFY_TITLE=$NOTIFY_TITLE \
                     -e EMAIL=$EMAIL \
                     -e PASSWORD=$PASSWORD \
                     ghcr.io/vogler/free-games-claimer
