name: Auto-EpicGame

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Docker container
        env:
          SHOW: 0
          NOTIFY: ${{ secrets.NOTIFY }}
          NOTIFY_TITLE: Auto-EpicGame
          EMAIL: ${{ secrets.EG_EMAIL }}
          PASSWORD: ${{ secrets.EG_PASSWORD }}
        run: |
          docker run --entrypoint "node" -e SHOW=$SHOW \
                                        -e LOGIN_TIMEOUT=30 \
                                        -e NOTIFY=$NOTIFY \
                                        -e NOTIFY_TITLE=$NOTIFY_TITLE \
                                        -e EMAIL=$EMAIL \
                                        -e PASSWORD=$PASSWORD \
                                        ghcr.io/vogler/free-games-claimer epic-games
