name: Free Games

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *' # Run at 1:00 AM UTC, or 9:00 AM CST

jobs:
  free-games:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vogler/free-games-claimer
      env:
        SHOW: 0
        NOTIFY: ${{ env.NOTIFY }}
        NOTIFY_TITLE: Auto-EpicGame
        EMAIL: ${{ env.EG_EMAIL }}
        PASSWORD: ${{ env.EG_PASSWORD }}
      ports:
        - 6080:6080
      volumes:
        - fgc:/fgc/data
    steps:
      - name: Run Docker
        run: |
          # do something here after container is started
